# Generated by Django 6.1 on 2026-09-16 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, default='', max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True, verbose_name='Mat. Req. No')),
                ('sap_number', models.CharField(blank=True, default='', max_length=50, verbose_name='SAP No')),
                ('project', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='Main HQ', max_length=200)),
                ('preparation_date', models.DateField(verbose_name='Preparation Date')),
                ('requisition_rec_date', models.DateField(blank=True, null=True, verbose_name='Requisition Rec. Date')),
                ('supply_period', models.CharField(blank=True, default='', max_length=200)),
                ('market_type', models.CharField(choices=[('local', 'Local Market'), ('foreign', 'Foreign Market')], default='local', max_length=20)),
                ('purchase_method', models.CharField(choices=[('general_tender', 'General Tender'), ('direct_order', 'Direct Order'), ('budgetary', 'Budgetary'), ('negotiation', 'Negotiation'), ('valid_contract', 'Valid Contract'), ('limited_tender', 'Limited Tender')], default='general_tender', max_length=20)),
                ('partial_order_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('chairman_approved', 'Chairman Approved'), ('rejected', 'Rejected'), ('vendor_selection', 'Vendor Selection'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('chairman_approved', models.BooleanField(default=False)),
                ('chairman_approved_date', models.DateField(blank=True, null=True)),
                ('budget_year', models.CharField(blank=True, default='', max_length=10)),
                ('gl_account', models.CharField(blank=True, default='', max_length=30)),
                ('emf_number', models.CharField(blank=True, default='', max_length=30)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Estimated Value (EGP)')),
                ('budget_type', models.CharField(choices=[('assets', 'Assets'), ('projects', 'Projects'), ('current', 'Current')], default='current', max_length=20)),
                ('budget_code', models.CharField(blank=True, default='', max_length=30)),
                ('book_number', models.CharField(blank=True, default='', max_length=30)),
                ('warranty_notes', models.TextField(blank=True, default='')),
                ('delivery_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='core.costcenter', verbose_name='Cost Center')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_created', to=settings.AUTH_USER_MODEL)),
                ('requesting_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='core.department', verbose_name='Requesting Department')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='core.vessel', verbose_name='Vessel')),
            ],
            options={
                'verbose_name': 'RFQ',
                'verbose_name_plural': 'RFQs',
                'ordering': ['-preparation_date', '-request_number'],
            },
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('unit', models.CharField(default='Piece', max_length=20, verbose_name='Unit')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity Needed')),
                ('inventory', models.CharField(blank=True, default='', max_length=50, verbose_name='Inventory')),
                ('store_code', models.CharField(blank=True, default='', max_length=30, verbose_name='Store Code')),
                ('maker', models.CharField(blank=True, default='', max_length=100, verbose_name='Maker')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.rfq')),
            ],
            options={
                'ordering': ['line_number'],
                'unique_together': {('rfq', 'line_number')},
            },
        ),
    ]
