# Generated by Django 6.1 on 2026-09-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='attachment',
            field=models.FileField(blank=True, default='', upload_to='rfq/attachments/%Y/%m/', verbose_name='Hard Copy'),
        ),
    ]
