# Generated by Django 6.1 on 2026-09-16 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rfq_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_rfq', models.BooleanField(default=True)),
                ('can_create_rfq', models.BooleanField(default=True)),
                ('can_view_vendors', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_config', to='core.department')),
            ],
            options={
                'verbose_name': 'Department Access',
                'verbose_name_plural': 'Department Access',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='AD sAMAccountName (e.g. 2669)', max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('requester', 'Requester'), ('purchaser', 'Purchaser'), ('manager', 'Manager'), ('admin', 'Admin')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('can_view_rfq', models.BooleanField(default=True)),
                ('can_create_rfq', models.BooleanField(default=False)),
                ('can_edit_rfq', models.BooleanField(default=False)),
                ('can_delete_rfq', models.BooleanField(default=False)),
                ('can_approve_rfq', models.BooleanField(default=False)),
                ('can_view_vendors', models.BooleanField(default=True)),
                ('can_create_vendors', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_view_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department')),
            ],
            options={
                'verbose_name': 'Employee Access',
                'verbose_name_plural': 'Employee Access',
                'ordering': ['employee_id'],
            },
        ),
    ]
