# Generated by Django 6.1.1 on 2026-09-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clientcode_location_mainactivity_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Note'),
        ),
    ]
