# Generated by Django 6.1.1 on 2026-09-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_costcenter_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcode',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Client Code'),
        ),
        migrations.AlterField(
            model_name='clientcode',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Location Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='agent_email1',
            field=models.TextField(blank=True, default='', verbose_name='Agent E-mail 1'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='agent_email2',
            field=models.TextField(blank=True, default='', verbose_name='Agent E-mail 2'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='agent_email3',
            field=models.TextField(blank=True, default='', verbose_name='Agent E-mail 3'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email1',
            field=models.TextField(blank=True, default='', verbose_name='E-mail 1'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email2',
            field=models.TextField(blank=True, default='', verbose_name='E-mail 2'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email3',
            field=models.TextField(blank=True, default='', verbose_name='E-mail 3'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='notes2',
            field=models.TextField(blank=True, default='', verbose_name='Notes 2'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.TextField(blank=True, default='', verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
