# Generated by Django 6.1.1 on 2026-09-25 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_clientcode_code_alter_clientcode_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='market',
            field=models.CharField(choices=[('local', 'Local'), ('foreign', 'Foreign')], db_index=True, default='local', max_length=10, verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='core.operation', verbose_name='Tender'),
        ),
    ]
